### ISSUE TITLE
Identation issue in roles/raspbian/tasks

### ISSUE THREAD

**Issue by mikedolx** [nicokaiser/rpi-camera-import#8]
Hi,

i tried to install the tool on my raspberry pi zero, but the playbook failed and complained about line 56 in `roles/raspbian/tasks/main.yml`. I fixed it locally and afterwards it was no issue any more. Here's what i've changed:

```
- name: Install usbmount hooks
  ansible.builtin.copy:
    src: 10_camera_import
    dest: /etc/usbmount/mount.d/10_camera_import
    mode: '0755' # added two spaces here.
```

I have fixed it locally on my pc and tried to push a branch to create a PR, but i wasn't allowed 🙄. Maybe you can bring that little fix in, by yourself.

Thanks,

BR;
Michael
